from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Iterable, Protocol

from trading_journal_collector.errors import (
    AccountMismatchError,
    AdapterUnavailableError,
    ExportValidationError,
    WriteCapableCredentialError,
)
from trading_journal_collector.models import (
    CredentialLease,
    NormalizedEvent,
    Platform,
    ProbeResult,
)


class ProcessLike(Protocol):
    def poll(self) -> int | None:
        ...

    def terminate(self) -> None:
        ...

    def kill(self) -> None:
        ...

    def wait(self, timeout: float | None = None) -> int:
        ...


ProcessLauncher = Callable[[list[str], Path], ProcessLike]


def _ini_value(value: str, name: str) -> str:
    if "\n" in value or "\r" in value:
        raise ValueError(f"{name} must not contain line breaks")
    return value


@dataclass(frozen=True)
class Mt4StartupConfig:
    """Renders short-lived startup config for a disposable MT4 terminal slot."""

    script_name: str = "TradeJournalExport_MT4"
    bootstrap_symbol: str = "EURUSD"
    period: str = "H1"
    enable_news: bool = False

    def render(self, credential: CredentialLease) -> str:
        login = _ini_value(credential.login, "login")
        password = _ini_value(credential.password_text(), "password")
        server = _ini_value(credential.server, "server")
        script = _ini_value(self.script_name, "script_name")
        symbol = _ini_value(self.bootstrap_symbol, "bootstrap_symbol")
        period = _ini_value(self.period, "period")

        lines = [
            "; generated by Trading Journal Collector; remove after exporter status",
            f"Login={login}",
            f"Password={password}",
            f"Server={server}",
            "EnableDDE=false",
            f"EnableNews={'true' if self.enable_news else 'false'}",
            "ExpertsEnable=true",
            "ExpertsDllImport=false",
            "ExpertsExpImport=false",
            "ExpertsTrades=false",
            f"Symbol={symbol}",
            f"Period={period}",
            f"Script={script}",
            "",
        ]
        return "\r\n".join(lines)


def parse_export_jsonl(path: Path) -> Iterable[dict]:
    with path.open("r", encoding="utf-8") as handle:
        for line_no, line in enumerate(handle, start=1):
            raw = line.strip()
            if not raw:
                continue
            try:
                item = json.loads(raw)
            except json.JSONDecodeError as exc:
                raise ExportValidationError(f"invalid MT4 JSONL at line {line_no}") from exc
            if not isinstance(item, dict):
                raise ExportValidationError(f"MT4 JSONL line {line_no} is not an object")
            if str(item.get("source", "")).upper() != Platform.MT4.value:
                raise ExportValidationError(f"MT4 JSONL line {line_no} has wrong source")
            yield item


def validate_export_status(status: dict) -> ProbeResult:
    connected = bool(status.get("connected", False))
    trade_allowed = bool(status.get("trade_allowed", True))
    login = str(status.get("account", ""))
    server = str(status.get("server", ""))

    if not connected:
        raise ExportValidationError("MT4 exporter reports terminal disconnected")
    if not login or not server:
        raise ExportValidationError("MT4 exporter did not report account/server")
    if trade_allowed:
        raise WriteCapableCredentialError(
            "MT4 reports ACCOUNT_TRADE_ALLOWED=true; use the Investor Password"
        )

    return ProbeResult(
        platform=Platform.MT4,
        login=login,
        server=server,
        connected=True,
        trade_allowed=False,
        read_only_restricted=True,
        restriction_reason="ACCOUNT_TRADE_ALLOWED=false",
    )


def _default_launcher(args: list[str], cwd: Path) -> ProcessLike:
    if os.name != "nt":
        raise AdapterUnavailableError("MT4 terminal launcher requires Windows")
    creationflags = getattr(subprocess, "CREATE_NEW_PROCESS_GROUP", 0)
    return subprocess.Popen(
        args,
        cwd=str(cwd),
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        creationflags=creationflags,
    )


class Mt4Adapter:
    """Disposable-slot MT4 read-only adapter.

    The golden terminal directory must already contain the compiled exporter at
    MQL4/Scripts/TradeJournalExport_MT4.ex4. Compilation/runtime validation is a
    Windows provisioning responsibility, not silently simulated here.
    """

    OUTPUT_FILE = "tj_export.jsonl"
    STATUS_FILE = "tj_status.json"
    CURSOR_FILE = "tj_since_ms.txt"

    def __init__(
        self,
        *,
        golden_terminal_dir: Path,
        work_root: Path,
        bootstrap_symbol: str = "EURUSD",
        terminal_exe_name: str = "terminal.exe",
        timeout_seconds: float = 90.0,
        poll_seconds: float = 0.2,
        launcher: ProcessLauncher | None = None,
    ) -> None:
        self.golden_terminal_dir = Path(golden_terminal_dir)
        self.work_root = Path(work_root)
        self.bootstrap_symbol = bootstrap_symbol.strip()
        self.terminal_exe_name = terminal_exe_name
        self.timeout_seconds = timeout_seconds
        self.poll_seconds = poll_seconds
        self.launcher = launcher or _default_launcher
        if not self.bootstrap_symbol:
            raise ValueError("bootstrap_symbol is required")
        if timeout_seconds < 5:
            raise ValueError("timeout_seconds is too small")
        if poll_seconds <= 0:
            raise ValueError("poll_seconds must be positive")

    def probe_read_only(self, credential: CredentialLease) -> ProbeResult:
        result, _ = self._run_export(
            credential,
            since_ms=int(time.time() * 1000),
            collect_events=False,
        )
        return result

    def collect_history(
        self,
        credential: CredentialLease,
        *,
        since_ms: int,
        until_ms: int,
    ) -> list[NormalizedEvent]:
        if since_ms < 0 or until_ms <= since_ms:
            raise ValueError("invalid MT4 history interval")
        _, events = self._run_export(
            credential,
            since_ms=since_ms,
            collect_events=True,
        )
        return events

    def _validate_template(self) -> None:
        if not self.golden_terminal_dir.is_dir():
            raise AdapterUnavailableError("MT4 golden terminal directory is missing")
        terminal = self.golden_terminal_dir / self.terminal_exe_name
        exporter = (
            self.golden_terminal_dir
            / "MQL4"
            / "Scripts"
            / "TradeJournalExport_MT4.ex4"
        )
        if not terminal.is_file():
            raise AdapterUnavailableError("MT4 terminal executable is missing from golden slot")
        if not exporter.is_file():
            raise AdapterUnavailableError(
                "compiled MT4 exporter EX4 is missing from golden slot"
            )

    def _run_export(
        self,
        credential: CredentialLease,
        *,
        since_ms: int,
        collect_events: bool,
    ) -> tuple[ProbeResult, list[NormalizedEvent]]:
        self._validate_template()
        self.work_root.mkdir(parents=True, exist_ok=True)
        slot = Path(tempfile.mkdtemp(prefix="tj-mt4-", dir=self.work_root))
        process: ProcessLike | None = None
        config_path: Path | None = None

        try:
            shutil.copytree(self.golden_terminal_dir, slot, dirs_exist_ok=True)
            files_dir = slot / "MQL4" / "Files"
            files_dir.mkdir(parents=True, exist_ok=True)
            output_path = files_dir / self.OUTPUT_FILE
            status_path = files_dir / self.STATUS_FILE
            cursor_path = files_dir / self.CURSOR_FILE

            for stale in (output_path, status_path, cursor_path):
                try:
                    stale.unlink()
                except FileNotFoundError:
                    pass

            cursor_path.write_text(str(max(0, int(since_ms))), encoding="ascii")
            config_path = slot / f"tj_start_{os.getpid()}_{time.time_ns()}.ini"
            config_text = Mt4StartupConfig(
                bootstrap_symbol=self.bootstrap_symbol
            ).render(credential)
            config_path.write_text(config_text, encoding="utf-8", newline="")

            terminal = slot / self.terminal_exe_name
            process = self.launcher(
                [str(terminal), str(config_path), "/portable"],
                slot,
            )

            deadline = time.monotonic() + self.timeout_seconds
            while not status_path.is_file():
                if time.monotonic() >= deadline:
                    raise ExportValidationError("MT4 exporter timed out")
                if process.poll() is not None:
                    # Give the filesystem one final chance after terminal exit.
                    if status_path.is_file():
                        break
                    raise ExportValidationError("MT4 terminal exited before exporter status")
                time.sleep(self.poll_seconds)

            # The broker password is no longer needed once the exporter has
            # emitted status. Best-effort overwrite before unlink; the entire
            # disposable slot is also destroyed below.
            if config_path is not None:
                self._overwrite_and_unlink(config_path)
                config_path = None

            try:
                status = json.loads(status_path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError) as exc:
                raise ExportValidationError("invalid MT4 exporter status") from exc
            if not isinstance(status, dict):
                raise ExportValidationError("invalid MT4 exporter status object")

            result = validate_export_status(status)
            if result.login != credential.login:
                raise AccountMismatchError(
                    f"MT4 login mismatch: expected {credential.login}, got {result.login}"
                )
            if result.server.casefold() != credential.server.casefold():
                raise AccountMismatchError(
                    f"MT4 server mismatch: expected {credential.server}, got {result.server}"
                )
            if str(status.get("code", "")) != "OK":
                raise ExportValidationError(
                    "MT4 exporter failed: " + str(status.get("code", "UNKNOWN"))[:96]
                )

            events: list[NormalizedEvent] = []
            if collect_events:
                if not output_path.is_file():
                    raise ExportValidationError("MT4 exporter output file is missing")
                for item in parse_export_jsonl(output_path):
                    account = str(item.get("account", ""))
                    server = str(item.get("server", ""))
                    event_id = str(item.get("event_id", ""))
                    if account != credential.login:
                        raise AccountMismatchError("MT4 event account mismatch")
                    if server.casefold() != credential.server.casefold():
                        raise AccountMismatchError("MT4 event server mismatch")
                    events.append(
                        NormalizedEvent(
                            source=Platform.MT4,
                            account=credential.login,
                            server=credential.server,
                            event_id=event_id,
                            payload=item,
                        )
                    )
            return result, events
        finally:
            if config_path is not None:
                self._overwrite_and_unlink(config_path)
            if process is not None:
                self._stop_process(process)
            self._remove_slot(slot)

    @staticmethod
    def _overwrite_and_unlink(path: Path) -> None:
        try:
            size = path.stat().st_size
            with path.open("r+b") as handle:
                handle.write(b"\x00" * size)
                handle.flush()
                os.fsync(handle.fileno())
        except (FileNotFoundError, OSError):
            pass
        try:
            path.unlink()
        except FileNotFoundError:
            pass
        except OSError:
            pass

    @staticmethod
    def _stop_process(process: ProcessLike) -> None:
        try:
            if process.poll() is not None:
                return
            process.terminate()
            try:
                process.wait(timeout=5)
            except Exception:
                process.kill()
                try:
                    process.wait(timeout=5)
                except Exception:
                    pass
        except Exception:
            pass

    @staticmethod
    def _remove_slot(slot: Path) -> None:
        last_error: OSError | None = None
        for _ in range(10):
            try:
                shutil.rmtree(slot)
                return
            except FileNotFoundError:
                return
            except OSError as exc:
                last_error = exc
                time.sleep(0.2)
        if last_error is not None:
            raise ExportValidationError("MT4 disposable slot cleanup failed") from last_error
