from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from trading_journal_collector.errors import ExportValidationError, WriteCapableCredentialError
from trading_journal_collector.models import CredentialLease, Platform, ProbeResult


def _ini_value(value: str, name: str) -> str:
    if "\n" in value or "\r" in value:
        raise ValueError(f"{name} must not contain line breaks")
    return value


@dataclass(frozen=True)
class Mt4StartupConfig:
    """Renders short-lived startup config for a disposable MT4 terminal slot."""

    script_name: str = "TradeJournalExport_MT4"
    enable_news: bool = False

    def render(self, credential: CredentialLease) -> str:
        login = _ini_value(credential.login, "login")
        password = _ini_value(credential.password_text(), "password")
        server = _ini_value(credential.server, "server")
        script = _ini_value(self.script_name, "script_name")

        lines = [
            "; generated by Trading Journal Collector; delete after terminal startup",
            f"Login={login}",
            f"Password={password}",
            f"Server={server}",
            "EnableDDE=false",
            f"EnableNews={'true' if self.enable_news else 'false'}",
            "ExpertsEnable=true",
            "ExpertsDllImport=false",
            "ExpertsExpImport=false",
            "ExpertsTrades=false",
            f"Script={script}",
            "",
        ]
        return "\r\n".join(lines)


def parse_export_jsonl(path: Path) -> Iterable[dict]:
    with path.open("r", encoding="utf-8") as handle:
        for line_no, line in enumerate(handle, start=1):
            raw = line.strip()
            if not raw:
                continue
            try:
                item = json.loads(raw)
            except json.JSONDecodeError as exc:
                raise ExportValidationError(f"invalid MT4 JSONL at line {line_no}") from exc
            if not isinstance(item, dict):
                raise ExportValidationError(f"MT4 JSONL line {line_no} is not an object")
            if str(item.get("source", "")).upper() != Platform.MT4.value:
                raise ExportValidationError(f"MT4 JSONL line {line_no} has wrong source")
            yield item


def validate_export_status(status: dict) -> ProbeResult:
    connected = bool(status.get("connected", False))
    trade_allowed = bool(status.get("trade_allowed", True))
    login = str(status.get("account", ""))
    server = str(status.get("server", ""))

    if not connected:
        raise ExportValidationError("MT4 exporter reports terminal disconnected")
    if not login or not server:
        raise ExportValidationError("MT4 exporter did not report account/server")
    if trade_allowed:
        raise WriteCapableCredentialError(
            "MT4 reports ACCOUNT_TRADE_ALLOWED=true; use the Investor Password"
        )

    return ProbeResult(
        platform=Platform.MT4,
        login=login,
        server=server,
        connected=True,
        trade_allowed=False,
        read_only_restricted=True,
        restriction_reason="ACCOUNT_TRADE_ALLOWED=false",
    )
